name = "PythonCall_tst"
uuid = "fb71cc4a-b88a-4c12-bac1-9ef90448d14f"
authors = ["Yzh <iulia.zhivolupova@gmail.com> and contributors"]
version = "0.1.0"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
PythonCall = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
